<a href="https://colab.research.google.com/github/deathstar1/Machine-Learning-Notebooks/blob/add-license-1/Basics_Lessons_Beginners.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basics for Beginners

In [19]:
import numpy as np

forecasts = np.array([1.0 ,0.6 , -1.3 ,  1.7])
actuals = np.array([1.0, 0.5,  -1.5 , 2.0])

In [20]:
print(forecasts -actuals)
errors = forecasts - actuals

[ 0.   0.1  0.2 -0.3]


# Simple techniques used in Data science is Root mean squared and Absolute mean etc. Let's look at mean squared.

### First square the values

In [21]:
squared = np.square(errors)
print(squared)

[0.   0.01 0.04 0.09]


### Mean the squared values

In [22]:
mean_squared =  squared.mean()
print(mean_squared)

0.035


### Root squared mean value which is RMSE

In [23]:
rmse = np.sqrt (mean_squared)
print(rmse)

0.18708286933869708


# Another technique is to get the mean of absolute values called Absolute mean error . You can use AME to not penalize your model with higher error values .In other words it is like a soft penalty.

In [27]:
absolutes = np.abs(errors)
print(absolutes)

[0.  0.1 0.2 0.3]


In [29]:
absolutes_mean = absolutes.mean()
print(absolutes_mean)

0.15
